#!/usr/bin/env python3
"""MRK Free Website Builder: turns a Website Factory spec + content into a portable static site."""
from __future__ import annotations
import argparse, json
from pathlib import Path
from html import escape

def page(title, body, business):
    nav=''.join(f'<a href="{p}">{n}</a>' for n,p in [("Home","index.html"),("Services","services.html"),("About","about.html"),("Projects","projects.html"),("Blog","blog.html"),("FAQ","faq.html"),("Contact","contact.html")])
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | {escape(business)}</title><meta name="description" content="{escape(title)} — professional services, practical solutions and direct contact."><link rel="stylesheet" href="assets/style.css"></head><body><header><strong>{escape(business)}</strong><nav>{nav}</nav></header><main>{body}</main><footer>© {escape(business)} — Built with MRK Free Website Factory</footer></body></html>"""

def build(spec, content, out):
    out=Path(out); (out/"assets").mkdir(parents=True,exist_ok=True)
    business=spec["brand"]; home=content["home"]
    pages={
      "index.html":f"<section class='hero'><h1>{escape(home['headline'])}</h1><p>{escape(home['intro'])}</p><a class='cta' href='contact.html'>{escape(home['cta'])}</a></section>",
      "services.html":"<h1>Services</h1><div class='grid'>"+''.join(f"<article><h2>{escape(x['title'])}</h2><p>{escape(x['body'])}</p></article>" for x in content["services"])+"</div>",
      "about.html":f"<h1>{escape(content['about']['headline'])}</h1><p>{escape(content['about']['body'])}</p><h2>Our approach</h2><p>Clear scope, transparent communication, quality delivery and ongoing support.</p>",
      "projects.html":f"<h1>{escape(content['projects']['headline'])}</h1><article><p>{escape(content['projects']['body'])}</p></article>",
      "blog.html":f"<h1>{escape(content['blog']['headline'])}</h1><article><p>{escape(content['blog']['body'])}</p></article>",
      "faq.html":"<h1>FAQ</h1>"+''.join(f"<details><summary>{escape(x['q'])}</summary><p>{escape(x['a'])}</p></details>" for x in content["faq"]),
      "contact.html":f"<h1>{escape(content['contact']['headline'])}</h1><p>{escape(content['contact']['body'])}</p><p>Replace this placeholder with your real email, WhatsApp and other approved contact details.</p>"
    }
    for filename,body in pages.items():
        title=filename.replace(".html","").replace("-"," ").title()
        (out/filename).write_text(page(title,body,business),encoding="utf-8")
    (out/"assets/style.css").write_text("""*{box-sizing:border-box}body{margin:0;font-family:system-ui,Arial;line-height:1.6;background:#0b1220;color:#eaf0f7}header{display:flex;justify-content:space-between;align-items:center;padding:18px 7%;border-bottom:1px solid #263246;position:sticky;top:0;background:#0b1220}nav{display:flex;gap:14px;flex-wrap:wrap}a{color:#dbeafe;text-decoration:none}main{max-width:1100px;margin:auto;padding:70px 7%}.hero{min-height:60vh;display:grid;align-content:center}.hero h1{font-size:clamp(2.4rem,7vw,5rem);margin:0}.hero p{font-size:1.15rem;max-width:760px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}article,details{padding:22px;border:1px solid #263246;border-radius:14px;background:#111b2d;margin:14px 0}.cta{display:inline-block;padding:12px 18px;border-radius:10px;background:#f2c94c;color:#111;margin-top:18px;font-weight:700}footer{text-align:center;padding:30px;border-top:1px solid #263246;color:#9fb0c3}""",encoding="utf-8")
    (out/"README.md").write_text("# "+business+" — Generated Static Website\n\nGenerated by MRK Free Website Factory. Review every page and replace placeholder contact details before publishing.\n",encoding="utf-8")

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--spec",default="data/website_factory/site_spec.json"); ap.add_argument("--content",default="data/website_factory/content.json"); ap.add_argument("--out",default="data/website_factory/site"); a=ap.parse_args()
    spec=json.loads(Path(a.spec).read_text(encoding="utf-8")); content=json.loads(Path(a.content).read_text(encoding="utf-8"))
    build(spec,content,a.out); print("Website generated:",a.out)

if __name__=="__main__": main()
