#!/usr/bin/env python3
"""MRK Free Website Builder: turns a Website Factory spec into a portable static site."""
from __future__ import annotations
import argparse, json
from pathlib import Path
from html import escape

def page(title, body, business):
    nav=''.join(f'<a href="{p}">{n}</a>' for n,p in [
        ("Home","index.html"),("Services","services.html"),("About","about.html"),
        ("Projects","projects.html"),("Blog","blog.html"),("FAQ","faq.html"),("Contact","contact.html")])
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | {escape(business)}</title>
<meta name="description" content="{escape(title)} — professional services, practical solutions and direct contact.">
<link rel="stylesheet" href="assets/style.css"></head>
<body><header><strong>{escape(business)}</strong><nav>{nav}</nav></header>
<main>{body}</main><footer>© {escape(business)} — Built with MRK Free Website Factory</footer></body></html>"""

def build(spec, out):
    out=Path(out); (out/"assets").mkdir(parents=True,exist_ok=True)
    business=spec["brand"]; niche=spec["niche"]; loc=spec.get("location","")
    common=f"<p>Professional {escape(niche.lower())} solutions with a clear process and direct support.</p><p>{escape(loc) if loc else 'Serving clients locally and online.'}</p>"
    pages={
      "index.html":f"<section class='hero'><h1>{escape(business)}</h1><h2>{escape(niche)}</h2>{common}<a class='cta' href='contact.html'>Get a Free Quote</a></section>",
      "services.html":f"<h1>Services</h1><div class='grid'>"+''.join(f"<article><h2>{escape(niche)} — Service {i}</h2><p>Professional, practical and client-focused service delivery.</p></article>" for i in range(1,5))+"</div>",
      "about.html":f"<h1>About {escape(business)}</h1>{common}<h2>Our approach</h2><p>Clear scope, transparent communication, quality delivery and ongoing support.</p>",
      "projects.html":"<h1>Projects</h1><div class='grid'><article><h2>Project Showcase</h2><p>Replace this placeholder with real case studies and measurable results.</p></article></div>",
      "blog.html":"<h1>Blog</h1><article><h2>Helpful guides and practical insights</h2><p>Publish useful, original articles here to build search visibility and trust.</p></article>",
      "faq.html":"<h1>FAQ</h1><details><summary>How do I request a quote?</summary><p>Use the contact page and describe your requirements.</p></details><details><summary>Do you work online?</summary><p>Yes, where the service can be delivered remotely.</p></details>",
      "contact.html":"<h1>Contact</h1><p>Tell us what you need and we will review your request.</p><a class='cta' href='mailto:hello@example.com'>Email Us</a>"
    }
    for filename,body in pages.items():
        title=filename.replace(".html","").replace("-"," ").title()
        (out/filename).write_text(page(title,body,business),encoding="utf-8")
    (out/"assets/style.css").write_text("""*{box-sizing:border-box}body{margin:0;font-family:system-ui,Arial;line-height:1.6;background:#0b1220;color:#eaf0f7}header{display:flex;justify-content:space-between;align-items:center;padding:18px 7%;border-bottom:1px solid #263246;position:sticky;top:0;background:#0b1220}nav{display:flex;gap:14px;flex-wrap:wrap}a{color:#dbeafe;text-decoration:none}main{max-width:1100px;margin:auto;padding:70px 7%}.hero{min-height:60vh;display:grid;align-content:center}.hero h1{font-size:clamp(2.4rem,7vw,5rem);margin:0}.hero h2{font-size:clamp(1.4rem,3vw,2.2rem)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}article,details{padding:22px;border:1px solid #263246;border-radius:14px;background:#111b2d;margin:14px 0}.cta{display:inline-block;padding:12px 18px;border-radius:10px;background:#f2c94c;color:#111;margin-top:18px;font-weight:700}footer{text-align:center;padding:30px;border-top:1px solid #263246;color:#9fb0c3}""",encoding="utf-8")
    (out/"README.md").write_text("# "+business+" — Generated Static Website\n\nGenerated by MRK Free Website Factory. Replace placeholder contact details before publishing.\n",encoding="utf-8")

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--spec",default="data/website_factory/site_spec.json"); ap.add_argument("--out",default="data/website_factory/site"); a=ap.parse_args()
    build(json.loads(Path(a.spec).read_text(encoding="utf-8")),a.out); print("Website generated:",a.out)

if __name__=="__main__": main()
