"""Deterministic conversion-event bookkeeping.

This records CTA placements generated by the content engine. It does NOT claim
that a click, lead, sale, or revenue event occurred. Real click/conversion
metrics must come from a connected analytics source.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

EVENTS_FILE = Path("data/conversion_events.json")


def record_conversion_placements(
    post_id: int,
    post_url: str,
    topic: str,
    placements: List[Dict[str, Any]],
) -> None:
    EVENTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    try:
        data = json.loads(EVENTS_FILE.read_text(encoding="utf-8")) if EVENTS_FILE.exists() else []
    except Exception:
        data = []
    if not isinstance(data, list):
        data = []

    for placement in placements:
        data.append({
            "event_type": "cta_placement",
            "post_id": post_id,
            "post_url": post_url,
            "topic": topic,
            "placement": placement,
            "recorded_at": datetime.now(timezone.utc).isoformat(),
            "metrics_source": "content_engine",
        })

    # Keep the repository state bounded.
    data = data[-5000:]
    EVENTS_FILE.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def build_conversion_report() -> Dict[str, Any]:
    try:
        data = json.loads(EVENTS_FILE.read_text(encoding="utf-8")) if EVENTS_FILE.exists() else []
    except Exception:
        data = []
    if not isinstance(data, list):
        data = []

    placement_counts: Dict[str, int] = {}
    post_count = set()
    for item in data:
        placement = str(item.get("placement", "unknown"))
        placement_counts[placement] = placement_counts.get(placement, 0) + 1
        if item.get("post_id") is not None:
            post_count.add(str(item["post_id"]))

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "cta_placements_total": len(data),
        "posts_with_cta_placements": len(post_count),
        "placement_counts": placement_counts,
        "clicks": None,
        "leads": None,
        "sales": None,
        "revenue": None,
        "metrics_source": "not_connected",
        "note": "Null metrics mean analytics is not connected; no performance numbers are invented.",
    }
